apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - manifests/ingress.yaml
# - manifests/deployment.yaml
resources:
- manifests/rollout.yaml
- manifests/db-sealedsecret.yaml
- manifests/db-statefulset.yaml
- manifests/client-service.yaml
- manifests/server-service.yaml
- manifests/broadcaster.yaml
- manifests/cronjob.yaml
- manifests/analysistemplate.yaml
images:
- name: PROJECT/IMAGE_BROADCASTER
  newName: nanyangcn/project-broadcaster
  newTag: master-fea1c88aa20e4a18c77faf1eac5f9c2a2a8082b1
- name: PROJECT/IMAGE_CLIENT
  newName: nanyangcn/project-client
  newTag: master-fea1c88aa20e4a18c77faf1eac5f9c2a2a8082b1
- name: PROJECT/IMAGE_CRONJOB
  newName: nanyangcn/project-cronjob
  newTag: master-fea1c88aa20e4a18c77faf1eac5f9c2a2a8082b1
- name: PROJECT/IMAGE_SERVER
  newName: nanyangcn/project-server
  newTag: master-fea1c88aa20e4a18c77faf1eac5f9c2a2a8082b1
namespace: project-master
