apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - manifests/deployment.yaml
resources:
- manifests/ingress.yaml
- manifests/rollout.yaml
- manifests/db-sealedsecret.yaml
- manifests/db-statefulset.yaml
- manifests/client-service.yaml
- manifests/server-service.yaml
- manifests/broadcaster.yaml
- manifests/cronjob.yaml
- manifests/analysistemplate.yaml
images:
- name: PROJECT/IMAGE_BROADCASTER
  newName: nanyangcn/project-broadcaster
  newTag: master-a969798f2dc53258151b87e08bfca17622f731b4
- name: PROJECT/IMAGE_CLIENT
  newName: nanyangcn/project-client
  newTag: master-a969798f2dc53258151b87e08bfca17622f731b4
- name: PROJECT/IMAGE_CRONJOB
  newName: nanyangcn/project-cronjob
  newTag: master-a969798f2dc53258151b87e08bfca17622f731b4
- name: PROJECT/IMAGE_SERVER
  newName: nanyangcn/project-server
  newTag: master-a969798f2dc53258151b87e08bfca17622f731b4
namespace: project-master
