apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - manifests/ingress.yaml
resources:
- manifests/rollout.yaml
# - manifests/deployment.yaml
- manifests/db-sealedsecret.yaml
- manifests/db-statefulset.yaml
- manifests/client-service.yaml
- manifests/server-service.yaml
- manifests/broadcaster.yaml
- manifests/cronjob.yaml
- manifests/analysistemplate.yaml
images:
- name: PROJECT/IMAGE_BROADCASTER
  newName: nanyangcn/project-broadcaster
  newTag: master-b0b56d79877b2e0685d636df15e644c3d8994fc8
- name: PROJECT/IMAGE_CLIENT
  newName: nanyangcn/project-client
  newTag: master-b0b56d79877b2e0685d636df15e644c3d8994fc8
- name: PROJECT/IMAGE_CRONJOB
  newName: nanyangcn/project-cronjob
  newTag: master-b0b56d79877b2e0685d636df15e644c3d8994fc8
- name: PROJECT/IMAGE_SERVER
  newName: nanyangcn/project-server
  newTag: master-b0b56d79877b2e0685d636df15e644c3d8994fc8
namespace: project-master
