apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - manifests/ingress.yaml
# - manifests/deployment.yaml
resources:
- manifests/rollout.yaml
- manifests/db-sealedsecret.yaml
- manifests/db-statefulset.yaml
- manifests/client-service.yaml
- manifests/server-service.yaml
- manifests/broadcaster.yaml
- manifests/cronjob.yaml
- manifests/analysistemplate.yaml
images:
- name: PROJECT/IMAGE_BROADCASTER
  newName: nanyangcn/project-broadcaster
  newTag: master-807c2bd842c548aff86dbb2f68a2b9a29f2f562f
- name: PROJECT/IMAGE_CLIENT
  newName: nanyangcn/project-client
  newTag: master-807c2bd842c548aff86dbb2f68a2b9a29f2f562f
- name: PROJECT/IMAGE_CRONJOB
  newName: nanyangcn/project-cronjob
  newTag: master-807c2bd842c548aff86dbb2f68a2b9a29f2f562f
- name: PROJECT/IMAGE_SERVER
  newName: nanyangcn/project-server
  newTag: master-807c2bd842c548aff86dbb2f68a2b9a29f2f562f
namespace: project-master
