apiVersion: v1
kind: Service
metadata:
  namespace: project-namespace
  name: project-client-svc
spec:
  type: NodePort
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 2348 
      targetPort: 3000