apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: project-namespace
  name: project-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: project-cronjob
            image: nanyangcn/project-cronjob
          restartPolicy: Never