apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project-namespace
  name: project-dep
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: volume0
          emptyDir: {}
      containers:
        - name: project-server
          image: PROJECT/IMAGE_SERVER
          resources:
            limits:
              cpu: "150m"
              memory: "300Mi"
          volumeMounts:
          - name: volume0
            mountPath: /usr/src/app/files
          envFrom:
          - secretRef:
              name: project-db-secret
        - name: project-client
          image: PROJECT/IMAGE_CLIENT
          resources:
            limits:
              cpu: "150m"
              memory: "300Mi"
          volumeMounts:
          - name: volume0
            mountPath: /usr/src/app/files