apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-ing
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: project-svc
          servicePort: 2345