apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: project-namespace
  name: project-ing
spec:
  rules:
  - http:
      paths:
      - path: /graphql
        backend:
          serviceName: project-server-svc
          servicePort: 2345
      - path: /picture
        backend:
          serviceName: project-server-svc
          servicePort: 2345
      - path: /
        backend:
          serviceName: project-server-svc
          servicePort: 2345