apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: project-master
  name: project-ing
  annotations:
    nginx.org/server-snippets: |
      location /static/ {
        root /usr/src/app/build;
      }
spec:
  rules:
  - http:
      paths:
      - path: /graphql
        backend:
          serviceName: project-server-svc
          servicePort: 2345
      - path: /picture
        backend:
          serviceName: project-server-svc
          servicePort: 2345
      - path: /
        backend:
          serviceName: project-client-svc
          servicePort: 2348