apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: project-dep
  namespace: project-namespace
spec:
  selector:
    matchLabels:
      app: project
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-usage-rate