apiVersion: v1
kind: Service
metadata:
  namespace: project-namespace
  name: project-server-svc
spec:
  type: ClusterIP
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 2345 
      targetPort: 3001