name: Release application

on:
  push:

jobs:
  build:
    name: Build, Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create image name and tag
      run: |
        echo "IMAGE_SERVER=${{ secrets.DOCKERHUB_USERNAME }}/project-server:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
        echo "IMAGE_CLIENT=${{ secrets.DOCKERHUB_USERNAME }}/project-client:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
        echo "IMAGE_CRONJOB=${{ secrets.DOCKERHUB_USERNAME }}/project-cronjob:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
        echo "IMAGE_BROADCASTER=${{ secrets.DOCKERHUB_USERNAME }}/project-broadcaster:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Server - Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        tags: ${{ env.IMAGE_SERVER }}
    - name: Client - Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./client
        file: ./client/Dockerfile
        push: true
        tags: ${{ env.IMAGE_CLIENT }}
    - name: Cronjob - Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./cronjob
        file: ./cronjob/Dockerfile
        push: true
        tags: ${{ env.IMAGE_CRONJOB }}
    - name: Broadcaster - Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./broadcaster
        file: ./broadcaster/Dockerfile
        push: true
        tags: ${{ env.IMAGE_BROADCASTER }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    - name: Deploy
      run: |-
        kubectl create namespace project-${GITHUB_REF#refs/heads/} || true
        kubectl config set-context --current --namespace=project-${GITHUB_REF#refs/heads/}
        ./kustomize edit set namespace project-${GITHUB_REF#refs/heads/}
        ./kustomize edit set image PROJECT/IMAGE_BROADCASTER=$IMAGE_BROADCASTER PROJECT/IMAGE_SERVER=$IMAGE_SERVER PROJECT/IMAGE_CLIENT=$IMAGE_CLIENT PROJECT/IMAGE_CRONJOB=$IMAGE_CRONJOB
    - name: Commit and push
      uses: EndBug/add-and-commit@v5
      with:
        add: './kustomization.yaml'
        message: New version release for gitops-app ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}